"""
IRC 37 corpus retrieval and lightweight Q&A utilities.

This module loads chunked knowledge artifacts generated by
tools/ingest_irc37_book.py and exposes:
1) BM25 search with metadata filters
2) Lightweight extractive answer synthesis with citations
"""

from __future__ import annotations

import json
import math
import re
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from threading import Lock
from typing import Any, Optional


TOKEN_RE = re.compile(r"[a-z0-9]+")
SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+|\n+")
EQUATION_HINT_RE = re.compile(
    r"(=|\beps[_a-z]*\b|\bepsilon\b|\bstrain\b|\bcdf\b|\bnf\b|\bnr\b|\bmr\b)",
    re.IGNORECASE,
)
EQUATION_QUERY_TERMS = {
    "equation",
    "formula",
    "nf",
    "nr",
    "cdf",
    "strain",
    "epsilon",
    "eps",
    "rutting",
    "fatigue",
    "modulus",
    "mr",
}


def tokenize(text: str) -> list[str]:
    return TOKEN_RE.findall(text.lower())


@dataclass(frozen=True)
class ChunkFilters:
    page_min: Optional[int] = None
    page_max: Optional[int] = None
    heading_contains: Optional[str] = None
    has_equation: Optional[bool] = None


@dataclass
class ChunkDoc:
    chunk_id: str
    page_start: int
    page_end: int
    heading: str
    text: str
    term_freq: Counter[str]
    length: int
    has_equation: bool


class BM25ChunkRetriever:
    """Small BM25 index over chunked knowledge rows."""

    def __init__(self, docs: list[ChunkDoc], k1: float = 1.5, b: float = 0.75):
        self.docs = docs
        self.k1 = k1
        self.b = b
        self.total_docs = len(docs)
        self.avg_doc_len = (
            sum(max(doc.length, 1) for doc in docs) / self.total_docs if self.total_docs else 1.0
        )

        doc_freq: Counter[str] = Counter()
        for doc in docs:
            for term in doc.term_freq.keys():
                doc_freq[term] += 1

        self.idf: dict[str, float] = {}
        for term, freq in doc_freq.items():
            # Standard BM25 IDF with +1 guard for positivity.
            self.idf[term] = math.log(1.0 + (self.total_docs - freq + 0.5) / (freq + 0.5))

    @classmethod
    def from_chunks_jsonl(cls, chunks_path: Path) -> "BM25ChunkRetriever":
        if not chunks_path.exists():
            raise FileNotFoundError(f"Knowledge chunks file not found: {chunks_path}")

        docs: list[ChunkDoc] = []
        with chunks_path.open("r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue

                row = json.loads(line)
                text = str(row.get("text", ""))
                tokens = tokenize(text)
                docs.append(
                    ChunkDoc(
                        chunk_id=str(row.get("chunk_id", "unknown")),
                        page_start=int(row.get("page_start", 0)),
                        page_end=int(row.get("page_end", row.get("page_start", 0))),
                        heading=str(row.get("heading", "Unclassified")),
                        text=text,
                        term_freq=Counter(tokens),
                        length=max(len(tokens), 1),
                        has_equation=bool(EQUATION_HINT_RE.search(text)),
                    )
                )

        return cls(docs)

    def _passes_filters(self, doc: ChunkDoc, filters: Optional[ChunkFilters]) -> bool:
        if filters is None:
            return True

        if filters.page_min is not None and doc.page_end < filters.page_min:
            return False
        if filters.page_max is not None and doc.page_start > filters.page_max:
            return False

        if filters.heading_contains:
            needle = filters.heading_contains.lower().strip()
            if needle and needle not in doc.heading.lower():
                return False

        if filters.has_equation is not None and doc.has_equation != filters.has_equation:
            return False

        return True

    def _bm25_score(self, query_terms: list[str], doc: ChunkDoc) -> float:
        if not query_terms:
            return 0.0

        score = 0.0
        unique_terms = set(query_terms)

        for term in unique_terms:
            tf = doc.term_freq.get(term, 0)
            if tf == 0:
                continue

            idf = self.idf.get(term, 0.0)
            denom = tf + self.k1 * (1.0 - self.b + self.b * (doc.length / self.avg_doc_len))
            score += idf * ((tf * (self.k1 + 1.0)) / denom)

        return score

    def _metadata_boost(self, query_terms: list[str], doc: ChunkDoc) -> float:
        qset = set(query_terms)
        if not qset:
            return 0.0

        heading_tokens = set(tokenize(doc.heading))
        heading_overlap = len(qset.intersection(heading_tokens))
        boost = 0.15 * heading_overlap

        if doc.has_equation and any(term in EQUATION_QUERY_TERMS for term in qset):
            boost += 0.25

        if "annex" in qset and "annex" in doc.heading.lower():
            boost += 0.15

        return boost

    def _build_snippet(self, text: str, query_terms: list[str], max_chars: int) -> str:
        clean = " ".join(text.split())
        if len(clean) <= max_chars:
            return clean

        qset = set(query_terms)
        best_sentence = ""
        best_overlap = -1

        for sentence in SENTENCE_SPLIT_RE.split(clean):
            sentence = sentence.strip()
            if len(sentence) < 20:
                continue
            overlap = len(qset.intersection(set(tokenize(sentence))))
            if overlap > best_overlap:
                best_overlap = overlap
                best_sentence = sentence

        if best_sentence:
            return best_sentence[:max_chars]
        return clean[:max_chars]

    def search(
        self,
        query: str,
        top_k: int = 5,
        filters: Optional[ChunkFilters] = None,
        snippet_length: int = 480,
    ) -> dict[str, Any]:
        query_terms = tokenize(query)
        if not query_terms:
            raise ValueError("Query must contain at least one alphanumeric term")

        scored: list[tuple[float, ChunkDoc]] = []
        candidate_chunks = 0

        for doc in self.docs:
            if not self._passes_filters(doc, filters):
                continue
            candidate_chunks += 1

            score = self._bm25_score(query_terms, doc) + self._metadata_boost(query_terms, doc)
            if score > 0.0:
                scored.append((score, doc))

        scored.sort(key=lambda item: item[0], reverse=True)
        top = scored[: max(1, top_k)]

        results = []
        for score, doc in top:
            results.append(
                {
                    "chunk_id": doc.chunk_id,
                    "page_start": doc.page_start,
                    "page_end": doc.page_end,
                    "heading": doc.heading,
                    "has_equation": doc.has_equation,
                    "score": round(score, 6),
                    "snippet": self._build_snippet(doc.text, query_terms, snippet_length),
                    "text": doc.text,
                }
            )

        return {
            "status": "ok",
            "query": query,
            "total_chunks": self.total_docs,
            "candidate_chunks": candidate_chunks,
            "matched_chunks": len(scored),
            "returned_chunks": len(results),
            "results": results,
        }


class IrcKnowledgeService:
    """Lazy-loading wrapper around BM25ChunkRetriever plus answer synthesis."""

    def __init__(self, knowledge_dir: Optional[Path] = None):
        if knowledge_dir is None:
            repo_root = Path(__file__).resolve().parents[2]
            knowledge_dir = repo_root / "knowledge" / "irc37_book"

        self.knowledge_dir = knowledge_dir
        self._retriever: Optional[BM25ChunkRetriever] = None
        self._lock = Lock()

    def _ensure_loaded(self) -> BM25ChunkRetriever:
        if self._retriever is not None:
            return self._retriever

        with self._lock:
            if self._retriever is None:
                chunks_path = self.knowledge_dir / "chunks.jsonl"
                self._retriever = BM25ChunkRetriever.from_chunks_jsonl(chunks_path)
        return self._retriever

    @staticmethod
    def _rank_sentences(query: str, results: list[dict[str, Any]]) -> list[tuple[float, str, dict[str, Any]]]:
        qset = set(tokenize(query))
        ranked: list[tuple[float, str, dict[str, Any]]] = []

        for hit in results:
            base = float(hit.get("score", 0.0))
            text = str(hit.get("text", ""))
            for sentence in SENTENCE_SPLIT_RE.split(text):
                sentence = sentence.strip()
                if len(sentence) < 28:
                    continue
                overlap = len(qset.intersection(set(tokenize(sentence))))
                if overlap == 0:
                    continue
                score = base + 0.35 * overlap + min(len(sentence), 180) / 1000.0
                ranked.append((score, sentence, hit))

        ranked.sort(key=lambda row: row[0], reverse=True)
        return ranked

    def search(
        self,
        query: str,
        top_k: int = 5,
        filters: Optional[ChunkFilters] = None,
        snippet_length: int = 480,
    ) -> dict[str, Any]:
        retriever = self._ensure_loaded()
        return retriever.search(query=query, top_k=top_k, filters=filters, snippet_length=snippet_length)

    def ask(
        self,
        query: str,
        top_k: int = 4,
        filters: Optional[ChunkFilters] = None,
        max_answer_chars: int = 900,
    ) -> dict[str, Any]:
        search_payload = self.search(query=query, top_k=top_k, filters=filters, snippet_length=560)
        results = list(search_payload.get("results", []))

        if not results:
            return {
                "status": "ok",
                "query": query,
                "answer": "No relevant IRC content was found for this query in the local corpus.",
                "citations": [],
                "retrieved_chunks": 0,
            }

        ranked_sentences = self._rank_sentences(query, results)

        selected: list[str] = []
        used_norm = set()
        used_chunks = set()

        for _, sentence, hit in ranked_sentences:
            norm = " ".join(sentence.lower().split())
            if norm in used_norm:
                continue
            if len(selected) >= 5:
                break

            selected.append(sentence)
            used_norm.add(norm)
            used_chunks.add(hit.get("chunk_id"))

            if sum(len(s) + 1 for s in selected) >= max_answer_chars:
                break

        if not selected:
            selected = [str(results[0].get("snippet", ""))]

        answer = " ".join(selected)
        answer = answer[:max_answer_chars].strip()

        citations = []
        for hit in results:
            citations.append(
                {
                    "chunk_id": hit.get("chunk_id"),
                    "page_start": hit.get("page_start"),
                    "page_end": hit.get("page_end"),
                    "heading": hit.get("heading"),
                    "score": hit.get("score"),
                }
            )

        return {
            "status": "ok",
            "query": query,
            "answer": answer,
            "citations": citations,
            "retrieved_chunks": len(results),
        }
